# netlify.toml

# This file intentionally left blank

[[redirects]]
from = "/output2.mbtiles"
  to = "/output2.mbtiles"
  status = 200
  force = true
  headers = { Content-Type = "application/x-protobuf", Cache-Control = "public, max-age=31536000" }

  

